/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2018, 2024 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
* File Name        : r_smc_interrupt.h
* Version          : 1.5.0
* Device(s)        : R7F702300BFABA
* Description      : This file implements interrupt priority setting.
***********************************************************************************************************************/

#ifndef SMC_INTC_H
#define SMC_INTC_H

/***********************************************************************************************************************
Macro definitions (Register bit)
***********************************************************************************************************************/

/***********************************************************************************************************************
Macro definitions
***********************************************************************************************************************/
#define INTC_IPIR_INTIPIR0_PRIORITY                            _INT_PRIORITY_15
#define INTC_IPIR_INTIPIR1_PRIORITY                            _INT_PRIORITY_15
#define INTC_IPIR_INTIPIR2_PRIORITY                            _INT_PRIORITY_15
#define INTC_IPIR_INTIPIR3_PRIORITY                            _INT_PRIORITY_15
#define INTC_INTC2_INTBRDC0_PRIORITY                           _INT_PRIORITY_15
#define INTC_INTC2_INTBRDC1_PRIORITY                           _INT_PRIORITY_15
#define INTC_INTC2_INTBRDC2_PRIORITY                           _INT_PRIORITY_15
#define INTC_INTC2_INTBRDC3_PRIORITY                           _INT_PRIORITY_15
#define INTC_ECM_INTECMMI_PRIORITY                             _INT_PRIORITY_15
#define INTC_ECM_INTECMDCLSMI_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I6_PRIORITY                          _INT_PRIORITY_15
#define INTC_EINT_INTEINTSW0_PRIORITY                          _INT_PRIORITY_15
#define INTC_EINT_INTEINTSW1_PRIORITY                          _INT_PRIORITY_15
#define INTC_EINT_INTEINTSW2_PRIORITY                          _INT_PRIORITY_15
#define INTC_EINT_INTEINTSW3_PRIORITY                          _INT_PRIORITY_15
#define INTC_ICU_M_INTICUPS_PRIORITY                           _INT_PRIORITY_15
#define INTC_ICU_M_INTICUP_PRIORITY                            _INT_PRIORITY_15
#define INTC_WDT_INTWDTB0TIT_PRIORITY                          _INT_PRIORITY_15
#define INTC_WDT_INTWDTB1TIT_PRIORITY                          _INT_PRIORITY_15
#define INTC_WDT_INTWDTB2TIT_PRIORITY                          _INT_PRIORITY_15
#define INTC_WDT_INTWDTB3TIT_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I8_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I10_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I12_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I14_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAPA_INTTAPA0IPEK0_PRIORITY                       _INT_PRIORITY_15
#define INTC_TAPA_INTTAPA0IVLY0_PRIORITY                       _INT_PRIORITY_15
#define INTC_SDMAC_INTSDMACERR_PRIORITY                        _INT_PRIORITY_15
#define INTC_DTS_INTDTSERR_PRIORITY                            _INT_PRIORITY_15
#define INTC_TPTM_INTTPTM0_PRIORITY                            _INT_PRIORITY_15
#define INTC_TPTM_INTTPTM1_PRIORITY                            _INT_PRIORITY_15
#define INTC_TPTM_INTTPTM2_PRIORITY                            _INT_PRIORITY_15
#define INTC_TPTM_INTTPTM3_PRIORITY                            _INT_PRIORITY_15
#define INTC_FACI0_INTFL0ENDNM_PRIORITY                        _INT_PRIORITY_15
#define INTC_FACI1_INTFL1ENDNM_PRIORITY                        _INT_PRIORITY_15
#define INTC_FACI2_INTFL2ENDNM_PRIORITY                        _INT_PRIORITY_15
#define INTC_DTS_INTDTS31TO0_PRIORITY                          _INT_PRIORITY_15
#define INTC_DTS_INTDTS63TO32_PRIORITY                         _INT_PRIORITY_15
#define INTC_DTS_INTDTS95TO64_PRIORITY                         _INT_PRIORITY_15
#define INTC_DTS_INTDTS127TO96_PRIORITY                        _INT_PRIORITY_15
#define INTC_DTS_INTDTSCT31TO0_PRIORITY                        _INT_PRIORITY_15
#define INTC_DTS_INTDTSCT63TO32_PRIORITY                       _INT_PRIORITY_15
#define INTC_DTS_INTDTSCT95TO64_PRIORITY                       _INT_PRIORITY_15
#define INTC_DTS_INTDTSCT127TO96_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH0_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH1_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH2_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH3_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH4_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH5_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH6_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH7_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH8_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH9_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH10_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH11_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH12_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH13_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH14_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC0_INTSDMAC0CH15_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH0_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH1_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH2_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH3_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH4_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH5_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH6_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH7_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH8_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH9_PRIORITY                      _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH10_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH11_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH12_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH13_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH14_PRIORITY                     _INT_PRIORITY_15
#define INTC_SDMAC1_INTSDMAC1CH15_PRIORITY                     _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM00_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM01_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM02_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM03_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM04_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM05_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM06_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM07_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM10_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM11_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM12_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM13_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM14_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM15_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM16_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM17_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM20_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM21_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM22_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM23_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM24_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM25_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM26_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM27_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM30_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM31_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM32_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM33_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM34_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM35_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM36_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0TIM37_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS00_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS01_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS02_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS03_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS04_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS05_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS06_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS07_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS10_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS11_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS12_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS13_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS14_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS15_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS16_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS17_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS20_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS21_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS22_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS23_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS24_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS25_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS26_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS27_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS30_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS31_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS32_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS33_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS34_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS35_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS36_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0MCS37_PRIORITY                        _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM00_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM01_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM02_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM03_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM10_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM11_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM12_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM13_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM20_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM21_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM22_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM23_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM30_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM31_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM32_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ATOM33_PRIORITY                       _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0AEI_PRIORITY                          _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ARU0_PRIORITY                         _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ARU1_PRIORITY                         _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ARU2_PRIORITY                         _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0CMP_PRIORITY                          _INT_PRIORITY_15
#define INTC_GTM_INTGTMA0ERR_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I5_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I6_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I7_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I8_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I9_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I10_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I11_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30I12_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30IPEK_PRIORITY                        _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30IVLY_PRIORITY                        _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30IER_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG30IWN_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I5_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I6_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I7_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I8_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I9_PRIORITY                          _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I10_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I11_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31I12_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31IPEK_PRIORITY                        _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31IVLY_PRIORITY                        _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31IER_PRIORITY                         _INT_PRIORITY_15
#define INTC_TSG3_INTTSG31IWN_PRIORITY                         _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM0TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM1TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM2TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM3TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM4TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM5TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM6TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM7TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM8TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_OSTM_INTOSTM9TINT_PRIORITY                        _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU00_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU01_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU02_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU03_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU10_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU11_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU12_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU13_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU20_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU21_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU22_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU23_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU30_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU31_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU32_PRIORITY                          _INT_PRIORITY_15
#define INTC_TPTM_INTTPTMU33_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ0SEC_PRIORITY                         _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ0ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ0I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ0I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ0I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ0I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ0I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ1ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ1I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ1I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ1I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ1I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ1I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ2ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ2I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ2I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ2I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ2I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_ADCJ_INTADCJ2I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0TX0_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0RX0_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0TX1_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0RX1_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0TX2_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0RX2_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0TX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0RX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0FE_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI0ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1TX0_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1RX0_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1TX1_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1RX1_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1TX2_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1RX2_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1TX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1RX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1FE_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI1ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI2TX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI2RX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI2FE_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI2ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI3TX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI3RX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI3FE_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI3ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI4TX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI4RX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI4FE_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI4ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI5TX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI5RX_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI5FE_PRIORITY                          _INT_PRIORITY_15
#define INTC_MSPI_INTMSPI5ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCANGERR0_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCANGRECC0_PRIORITY                   _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN0ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN0REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN0TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN1ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN1REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN1TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN2ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN2REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN2TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN3ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN3REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN3TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN4ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN4REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN4TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN5ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN5REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN5TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN6ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN6REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN6TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN7ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN7REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN7TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCANGERR1_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCANGRECC1_PRIORITY                   _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN8ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN8REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN8TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN9ERR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN9REC_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN9TRX_PRIORITY                     _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN10ERR_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN10REC_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN10TRX_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN11ERR_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN11REC_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN11TRX_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN12ERR_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN12REC_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN12TRX_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN13ERR_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN13REC_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN13TRX_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN14ERR_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN14REC_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN14TRX_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN15ERR_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN15REC_PRIORITY                    _INT_PRIORITY_15
#define INTC_RS_CANFD_INTRCAN15TRX_PRIORITY                    _INT_PRIORITY_15
#define INTC_SCI3_INTSCI30ERI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI30RXI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI30TXI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI30TEI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI31ERI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI31RXI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI31TXI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI31TEI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI32ERI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI32RXI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI32TXI_PRIORITY                         _INT_PRIORITY_15
#define INTC_SCI3_INTSCI32TEI_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ0I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ0I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ0I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ0I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ1I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ1I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ1I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ1I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ2I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ2I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ2I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ2I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ3I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ3I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ3I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUJ_INTTAUJ3I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I5_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I7_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I9_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I11_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I13_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD0I15_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I5_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I6_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I7_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I8_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I9_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I10_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I11_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I12_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I13_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I14_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD1I15_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I2_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I3_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I4_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I5_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I6_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I7_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I8_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I9_PRIORITY                          _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I10_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I11_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I12_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I13_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I14_PRIORITY                         _INT_PRIORITY_15
#define INTC_TAUD_INTTAUD2I15_PRIORITY                         _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN30_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN30UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN30UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN30UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN31_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN31UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN31UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN31UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN32_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN32UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN32UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN32UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN33_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN33UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN33UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN33UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN34_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN34UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN34UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN34UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN35_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN35UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN35UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN35UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN36_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN36UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN36UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN36UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN37_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN37UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN37UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN37UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN38_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN38UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN38UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN38UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN39_PRIORITY                          _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN39UR0_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN39UR1_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN39UR2_PRIORITY                       _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN310_PRIORITY                         _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN310UR0_PRIORITY                      _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN310UR1_PRIORITY                      _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN310UR2_PRIORITY                      _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN311_PRIORITY                         _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN311UR0_PRIORITY                      _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN311UR1_PRIORITY                      _INT_PRIORITY_15
#define INTC_RLIN3_INTRLIN311UR2_PRIORITY                      _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT0SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT0RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT1SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT1RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT2SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT2RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT3SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT3RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT4SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT4RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT5SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT5RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT6SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT6RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT7SI_PRIORITY                        _INT_PRIORITY_15
#define INTC_RSENT_INTRSENT7RI_PRIORITY                        _INT_PRIORITY_15
#define INTC_TPBA_INTTPBA0IPRD_PRIORITY                        _INT_PRIORITY_15
#define INTC_TPBA_INTTPBA0IDTY_PRIORITY                        _INT_PRIORITY_15
#define INTC_TPBA_INTTPBA0IPAT_PRIORITY                        _INT_PRIORITY_15
#define INTC_TPBA_INTTPBA1IPRD_PRIORITY                        _INT_PRIORITY_15
#define INTC_TPBA_INTTPBA1IDTY_PRIORITY                        _INT_PRIORITY_15
#define INTC_TPBA_INTTPBA1IPAT_PRIORITY                        _INT_PRIORITY_15
#define INTC_ENCA_INTENCA0IOV_PRIORITY                         _INT_PRIORITY_15
#define INTC_ENCA_INTENCA0IUD_PRIORITY                         _INT_PRIORITY_15
#define INTC_ENCA_INTENCA0I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_ENCA_INTENCA0I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_ENCA_INTENCA0IEC_PRIORITY                         _INT_PRIORITY_15
#define INTC_ENCA_INTENCA1IOV_PRIORITY                         _INT_PRIORITY_15
#define INTC_ENCA_INTENCA1IUD_PRIORITY                         _INT_PRIORITY_15
#define INTC_ENCA_INTENCA1I0_PRIORITY                          _INT_PRIORITY_15
#define INTC_ENCA_INTENCA1I1_PRIORITY                          _INT_PRIORITY_15
#define INTC_ENCA_INTENCA1IEC_PRIORITY                         _INT_PRIORITY_15
#define INTC_PORT_INTP0_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP1_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP2_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP3_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP4_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP5_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP6_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP7_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP8_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP9_PRIORITY                               _INT_PRIORITY_15
#define INTC_PORT_INTP10_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP11_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP12_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP13_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP14_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP15_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP16_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP17_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP18_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP19_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP20_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP21_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP22_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP23_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP24_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP25_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP26_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP27_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP28_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP29_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP30_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP31_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP32_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP33_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP34_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP35_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP36_PRIORITY                              _INT_PRIORITY_15
#define INTC_PORT_INTP37_PRIORITY                              _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH0_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH1_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH2_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH3_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH4_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH5_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH6_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S0INTCH7_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH0_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH1_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH2_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH3_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH4_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH5_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH6_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5S_INTPSI5S1INTCH7_PRIORITY                    _INT_PRIORITY_15
#define INTC_PSI5_INTPSI50SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI50RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI50TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI51SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI51RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI51TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI52SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI52RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI52TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI53SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI53RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PSI5_INTPSI53TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0TXCMP_PRIORITY                     _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0TXEX_PRIORITY                      _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0RXCMP_PRIORITY                     _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0RXEX_PRIORITY                      _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0ICLCR_PRIORITY                     _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0INTCH0_PRIORITY                    _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0INTCH1_PRIORITY                    _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0INTCH2_PRIORITY                    _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0INTCH3_PRIORITY                    _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0STR_PRIORITY                       _INT_PRIORITY_15
#define INTC_RHSIF_INTRHSIF0ERR_PRIORITY                       _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0LINE0_PRIORITY                       _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0LINE1_PRIORITY                       _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0TIM0_PRIORITY                        _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0TIM1_PRIORITY                        _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0TIM2_PRIORITY                        _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0FDA_PRIORITY                         _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0FW_PRIORITY                          _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0OW_PRIORITY                          _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0OT_PRIORITY                          _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0IQF_PRIORITY                         _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA0IQE_PRIORITY                         _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1LINE0_PRIORITY                       _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1LINE1_PRIORITY                       _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1TIM0_PRIORITY                        _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1TIM1_PRIORITY                        _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1TIM2_PRIORITY                        _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1FDA_PRIORITY                         _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1FW_PRIORITY                          _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1OW_PRIORITY                          _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1OT_PRIORITY                          _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1IQF_PRIORITY                         _INT_PRIORITY_15
#define INTC_FLXA_INTFLXA1IQE_PRIORITY                         _INT_PRIORITY_15
#define INTC_ETNB_INTETNB0DATA_PRIORITY                        _INT_PRIORITY_15
#define INTC_ETNB_INTETNB0ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_ETNB_INTETNB0MNG_PRIORITY                         _INT_PRIORITY_15
#define INTC_ETNB_INTETNB0MAC_PRIORITY                         _INT_PRIORITY_15
#define INTC_ETNB_INTETNB1DATA_PRIORITY                        _INT_PRIORITY_15
#define INTC_ETNB_INTETNB1ERR_PRIORITY                         _INT_PRIORITY_15
#define INTC_ETNB_INTETNB1MNG_PRIORITY                         _INT_PRIORITY_15
#define INTC_ETNB_INTETNB1MAC_PRIORITY                         _INT_PRIORITY_15
#define INTC_ETNB_INTETNB1STA_PRIORITY                         _INT_PRIORITY_15
#define INTC_RTCA_INTRTCA01S_PRIORITY                          _INT_PRIORITY_15
#define INTC_RTCA_INTRTCA0AL_PRIORITY                          _INT_PRIORITY_15
#define INTC_RTCA_INTRTCA0R_PRIORITY                           _INT_PRIORITY_15
#define INTC_OTS_INTOTSOTE_PRIORITY                            _INT_PRIORITY_15
#define INTC_OTS_INTOTSOTI_PRIORITY                            _INT_PRIORITY_15
#define INTC_OTS_INTOTSOTULI_PRIORITY                          _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG00_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG01_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG02_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG10_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG11_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG12_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG20_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG21_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG22_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG30_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG31_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_INTPWGCG32_PRIORITY                      _INT_PRIORITY_15
#define INTC_PWM_DIAG_PWSD_INT_QFULL_PRIORITY                  _INT_PRIORITY_15
#define INTC_CXPI_INTCXP10TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP10RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP10SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP11TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP11RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP11SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP12TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP12RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP12SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP13TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP13RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_CXPI_INTCXP13SI_PRIORITY                          _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC0EE_PRIORITY                          _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC0RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC0TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC0TEI_PRIORITY                         _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC1EE_PRIORITY                          _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC1RI_PRIORITY                          _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC1TI_PRIORITY                          _INT_PRIORITY_15
#define INTC_RIIC_INTRIIC1TEI_PRIORITY                         _INT_PRIORITY_15
#define INTC_LPS_INTCWEND_PRIORITY                             _INT_PRIORITY_15
#define INTC_LPS_INTDPE_PRIORITY                               _INT_PRIORITY_15
#define INTC_MMCA_INTMMCA0_PRIORITY                            _INT_PRIORITY_15
#define INTC_BHP_INTDCUDEGRADPE_PRIORITY                       _INT_PRIORITY_15
#define INTC_ICU_M_INTICUMFATALERR_PRIORITY                    _INT_PRIORITY_15
#define INTC_PORT_INTDNFA1WUF0_PRIORITY                        _INT_PRIORITY_15
#define INTC_PORT_INTDNFA1WUF1_PRIORITY                        _INT_PRIORITY_15
#define INTC_PORT_INTDNFA2WUF0_PRIORITY                        _INT_PRIORITY_15
#define INTC_PORT_INTDNFA2WUF1_PRIORITY                        _INT_PRIORITY_15
#define INTC_PORT_INTDNFA0WUF0_PRIORITY                        _INT_PRIORITY_15
#define INTC_PORT_INTDNFA0WUF1_PRIORITY                        _INT_PRIORITY_15
#define INTC_WDT_INTWDTBATIT_PRIORITY                          _INT_PRIORITY_15
#define INTC_PORT_INTDCUTDI_PRIORITY                           _INT_PRIORITY_15
#define INTC_PORT_INTTAPA0ESO_PRIORITY                         _INT_PRIORITY_15
#define INTC_PORT_INTTAPA1ESO_PRIORITY                         _INT_PRIORITY_15

/***********************************************************************************************************************
Typedef definitions
***********************************************************************************************************************/

/***********************************************************************************************************************
Global functions
***********************************************************************************************************************/
void R_Interrupt_Create(void);
void INTETNB0DATA_enable_interrupt(void);
void INTETNB0DATA_disable_interrupt(void);
void INTETNB0ERR_enable_interrupt(void);
void INTETNB0ERR_disable_interrupt(void);
void INTETNB0MNG_enable_interrupt(void);
void INTETNB0MNG_disable_interrupt(void);
void INTETNB0MAC_enable_interrupt(void);
void INTETNB0MAC_disable_interrupt(void);
/* Start user code for function. Do not edit comment generated here */
/* End user code. Do not edit comment generated here */
#endif
